version: "3"
services:
  cluster:
    image: cluster
    build: ./
    volumes:
      - ./storage:/app/storage
      - ./scripts:/scripts
      - ./confs/hosts.txt:/etc/hosts
      - ./confs/nginx.conf:/etc/nginx/nginx.conf
      - ./confs/start.sh:/start.sh
    environment:
      CONFIG_PATH: "config.cluster"
    command: ["bash", "/start.sh"]
#    ports:
#      - 8080:8080
    networks:
      - default
